-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 15:08:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aihdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aihdb` ;

-- -----------------------------------------------------
-- Schema aihdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aihdb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema slsaledb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `slsaledb` ;

-- -----------------------------------------------------
-- Schema slsaledb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `slsaledb` DEFAULT CHARACTER SET utf8 ;
USE `aihdb` ;

-- -----------------------------------------------------
-- Table `aihdb`.`aih_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aihdb`.`aih_user` ;

CREATE TABLE IF NOT EXISTS `aihdb`.`aih_user` (
  `id` BIGINT NOT NULL,
  `loginCode` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NULL,
  `password2` VARCHAR(60) NULL,
  `userName` VARCHAR(60) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `userAddress` VARCHAR(45) NULL,
  `roleId` VARCHAR(45) NULL,
  `roleName` VARCHAR(45) NULL,
  `iconPath` VARCHAR(200) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aihdb`.`aih_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aihdb`.`aih_role` ;

CREATE TABLE IF NOT EXISTS `aihdb`.`aih_role` (
  `roleId` BIGINT NOT NULL,
  `roleName` VARCHAR(45) NULL,
  `roleCode` VARCHAR(45) NULL,
  `createDate` DATETIME NULL,
  `isStart` INT NULL,
  `createBy` VARCHAR(45) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aihdb`.`aih_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aihdb`.`aih_authority` ;

CREATE TABLE IF NOT EXISTS `aihdb`.`aih_authority` (
  `id` BIGINT NOT NULL,
  `roleId` BIGINT NULL,
  `functionId` BIGINT NULL,
  `userTypeId` BIGINT NULL,
  `createTime` DATETIME NULL,
  `createBy` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aihdb`.`aih_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aihdb`.`aih_function` ;

CREATE TABLE IF NOT EXISTS `aihdb`.`aih_function` (
  `id` BIGINT NOT NULL,
  `functionCode` VARCHAR(45) NULL,
  `functionName` VARCHAR(45) NULL,
  `funcUrl` VARCHAR(255) NULL,
  `parentId` BIGINT NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `slsaledb` ;

-- -----------------------------------------------------
-- Table `slsaledb`.`affiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`affiche` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`affiche` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '编码',
  `title` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '内容',
  `publisher` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '发布人',
  `publishTime` DATETIME NULL DEFAULT NULL COMMENT '发布时间',
  `startTime` DATETIME NULL DEFAULT NULL COMMENT '生效时间',
  `endTime` DATETIME NULL DEFAULT NULL COMMENT '失效时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`au_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`au_authority` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`au_authority` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `roleId` BIGINT(20) NULL DEFAULT NULL COMMENT '角色ID',
  `functionId` BIGINT(20) NULL DEFAULT NULL COMMENT '功能ID',
  `userTypeId` BIGINT(20) NULL DEFAULT NULL COMMENT '用户类型ID',
  `creationTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `createdBy` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1706
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`au_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`au_function` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`au_function` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `functionCode` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '功能编码',
  `functionName` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '功能名称',
  `funcUrl` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '功能URL',
  `parentId` BIGINT(20) NULL DEFAULT NULL,
  `creationTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`au_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`au_role` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`au_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `roleCode` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '角色编码',
  `roleName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '角色名称',
  `createDate` DATE NULL DEFAULT NULL COMMENT '创建日期',
  `isStart` INT(10) NULL DEFAULT NULL COMMENT '是否启用（0、未启用1、启用）',
  `createdBy` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`au_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`au_user` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`au_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `loginCode` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '登录账号',
  `password` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '登录密码（初始密码为证件号码后六位）',
  `password2` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '二级密码（初始密码为证件号码后六位）',
  `userName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '用户真实姓名',
  `sex` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '性别',
  `birthday` DATE NULL DEFAULT NULL COMMENT '生日',
  `cardType` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '证件类型id',
  `cardTypeName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '证件类型名称',
  `idCard` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '证件号码',
  `country` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '收货国家',
  `mobile` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '手机',
  `email` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'email',
  `userAddress` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '收获地址',
  `postCode` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '邮编',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '注册时间',
  `referId` BIGINT(20) NULL DEFAULT NULL COMMENT '推荐人id（默认为当前登录用户id）',
  `referCode` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '推荐人编码（默认为当前登录用户loginCode）',
  `roleId` BIGINT(20) NULL DEFAULT NULL COMMENT '所属角色ID',
  `roleName` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '所属角色名称',
  `userType` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '用户类型id',
  `userTypeName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '用户类型名称',
  `isStart` INT(10) NULL DEFAULT NULL COMMENT '是否启用（1、启用2、未启用）',
  `lastUpdateTime` DATETIME NULL DEFAULT NULL COMMENT '最新更新时间',
  `lastLoginTime` DATETIME NULL DEFAULT NULL COMMENT '最后登录时间',
  `bankAccount` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '开户卡号',
  `bankName` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '开户行',
  `accountHolder` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '开户人',
  `idCardPicPath` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '身份证照片存放路径',
  `bankPicPath` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '银行卡照片存放路径',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`basics_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`basics_parameter` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`basics_parameter` (
  `ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `NAME` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `CODE` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `VALUE` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `DR` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '系统基础支撑数据信息';


-- -----------------------------------------------------
-- Table `slsaledb`.`data_dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`data_dictionary` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`data_dictionary` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `typeCode` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '类型编码',
  `typeName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '类型名称',
  `valueId` INT(20) NULL DEFAULT NULL COMMENT '类型值ID',
  `valueName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '类型值Name',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`goods_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`goods_info` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`goods_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goodsSN` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '商品编码',
  `goodsName` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '商品名称',
  `goodsFormat` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '商品规格',
  `marketPrice` DOUBLE NULL DEFAULT NULL COMMENT '市场价',
  `realPrice` DOUBLE NULL DEFAULT NULL COMMENT '优惠价格',
  `state` INT(10) NULL DEFAULT NULL COMMENT '状态（1、上架、2、下架）',
  `note` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '商品说明',
  `num` INT(20) NULL DEFAULT '0' COMMENT '库存数量',
  `unit` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '单位',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `lastUpdateTime` DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
  `createdBy` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`goods_pack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`goods_pack` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`goods_pack` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goodsPackName` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '套餐名称',
  `goodsPackCode` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '套餐编码',
  `typeId` INT(20) NULL DEFAULT NULL COMMENT '套餐类型ID',
  `typeName` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '套餐类型NAME',
  `totalPrice` DOUBLE NULL DEFAULT NULL COMMENT '套餐总价（系统生成，保存时根据相关商品的优惠价*数量计算生成）',
  `state` INT(10) NULL DEFAULT NULL COMMENT '状态（1、上架2、下架）',
  `note` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '备注说明',
  `num` INT(20) NULL DEFAULT '0' COMMENT '库存数量',
  `createdBy` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '创建人',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `lastUpdateTime` DATETIME NULL DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`goods_pack_affiliated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`goods_pack_affiliated` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`goods_pack_affiliated` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `goodsPackId` BIGINT(20) NULL DEFAULT NULL COMMENT '商品套餐主表ID',
  `goodsInfoId` BIGINT(20) NULL DEFAULT NULL COMMENT '商品ID',
  `goodsNum` INT(20) NULL DEFAULT NULL COMMENT '商品数量',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`info_annexes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`info_annexes` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`info_annexes` (
  `ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'GOODS_ID',
  `INFO_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `NAME` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '货品编码',
  `URL` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `STATE` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `TYPE` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `UPLOAD_TIME` DATE NULL DEFAULT NULL,
  `SIZE` DECIMAL(8,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '资讯附件表';


-- -----------------------------------------------------
-- Table `slsaledb`.`information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`information` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`information` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '内容',
  `state` INT(20) NULL DEFAULT '1' COMMENT '发布状态（0、未发布 1、发布）默认为发布',
  `publisher` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '发布人',
  `publishTime` DATETIME NULL DEFAULT NULL COMMENT '发布时间',
  `typeId` INT(10) NULL DEFAULT NULL COMMENT '附件类型ID',
  `typeName` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '附件类型NAME',
  `fileName` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '附件名称',
  `filePath` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '附件存放路径',
  `fileSize` DOUBLE NULL DEFAULT NULL COMMENT '附件大小',
  `uploadTime` DATETIME NULL DEFAULT NULL COMMENT '上传时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`inventory` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`inventory` (
  `ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `GOODS_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `NUM` DECIMAL(8,0) NULL DEFAULT NULL,
  `STATE` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '库存表';


-- -----------------------------------------------------
-- Table `slsaledb`.`leave_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`leave_message` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`leave_message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `createdBy` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '留言用户code',
  `messageCode` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '留言编码',
  `messageTitle` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '留言标题',
  `messageContent` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '留言内容',
  `state` INT(10) NULL DEFAULT NULL COMMENT '状态（1、已回复0、未回复）',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '留言时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`multi_lan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`multi_lan` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`multi_lan` (
  `ELEMENT_ID` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '元素内容ID',
  `PAGE_PATH` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '页面文件路径',
  `SCN` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '简体中文',
  `TCN` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '繁体中文',
  `EN` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '英文',
  `JP` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '日文',
  `KR` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '韩文',
  `FR` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '法文',
  `RA` VARCHAR(3000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '俄文',
  PRIMARY KEY (`ELEMENT_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '多语言内容';


-- -----------------------------------------------------
-- Table `slsaledb`.`order_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`order_info` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`order_info` (
  `ORDER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ORDER_ID',
  `LIST_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ORDER_TIME` DATE NULL DEFAULT NULL COMMENT '订购时间',
  `ORDER_SN` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '订购单号',
  `PICK_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '收货用户ID',
  `REPEAT_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消PV',
  `BASE_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '基本PV',
  `SERVICE_FEE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '服务费',
  `SHIP_FRE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '快递费',
  `TAX` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '税费',
  `COUNTRY` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '收货国家',
  `TEL` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '联系电话',
  `MOBILE` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '手机',
  `EMAIL` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '电邮',
  `USER_ADDRESS` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '家庭住址',
  `POSTCODE` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '邮政编码',
  `STAT` DECIMAL(6,0) NULL DEFAULT NULL COMMENT '0新建,1已提交,2已审核,3已发货,4已收货,5审核未通过',
  `SHIP_TYPE` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '快递类型',
  `SHIP_NUM` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '快递单号',
  `SHIP_TIME` DATE NULL DEFAULT NULL COMMENT '发货时间',
  `RECEIVE_TIME` DATE NULL DEFAULT NULL COMMENT '收货确认时间',
  `SHIP_NOTE` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '送货说明',
  `buy_user_id` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '付款用户ID',
  PRIMARY KEY (`ORDER_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户订购记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`order_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`order_list` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`order_list` (
  `LIST_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'LIST_ID',
  `GOODS_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `GOODS_SN` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '货品编码',
  `GOODS_NAME` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '货品名称',
  `GOODS_FORMAT` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '货品规格',
  `GOODS_NUM` DECIMAL(9,0) NULL DEFAULT NULL COMMENT '数量',
  `EACH_PRICE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '单价',
  `SUM_PRICE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '总价',
  `DISCOUNT` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '折扣',
  `REAL_PRICE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '实际价格',
  `CURRENCY` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '货币种类',
  `REAL_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '实际PV',
  `PV_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT 'PV折算率',
  PRIMARY KEY (`LIST_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户订购商品表';


-- -----------------------------------------------------
-- Table `slsaledb`.`reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`reply` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`reply` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `messageId` BIGINT(20) NULL DEFAULT NULL COMMENT '留言ID（主表）',
  `replyContent` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '回复内容',
  `createdBy` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '回复人',
  `createTime` DATETIME NULL DEFAULT NULL COMMENT '回复时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`s_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`s_role` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`s_role` (
  `roleId` INT(11) NOT NULL,
  `roleName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `slsaledb`.`s_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`s_permission` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`s_permission` (
  `id` INT(11) NOT NULL,
  `permissionName` VARCHAR(255) NULL DEFAULT NULL,
  `roleId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `permission_fk` (`roleId` ASC),
  CONSTRAINT `permission_fk`
    FOREIGN KEY (`roleId`)
    REFERENCES `slsaledb`.`s_role` (`roleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `slsaledb`.`s_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`s_user` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`s_user` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `pwd` VARCHAR(255) NULL DEFAULT NULL,
  `roleId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_fk` (`roleId` ASC),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`roleId`)
    REFERENCES `slsaledb`.`s_role` (`roleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `slsaledb`.`uploadtemp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`uploadtemp` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`uploadtemp` (
  `uploader` VARCHAR(20) NULL DEFAULT NULL,
  `uploadType` VARCHAR(20) NULL DEFAULT NULL,
  `uploadFilePath` VARCHAR(200) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `slsaledb`.`user_account_201312`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_account_201312` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_account_201312` (
  `ACCOUNT_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ACCOUNT_ID',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ACCOUNT_DATE` DATE NULL DEFAULT NULL COMMENT '日期',
  `STAT` DECIMAL(6,0) NULL DEFAULT NULL COMMENT '0开放,1奖励完成,2积分消费完成',
  `BASE_IN` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '基本入账',
  `BASE_OUT` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '基本出账',
  `BASE_BALANCE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '基本余额',
  `REPEAT_IN` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消入账',
  `REPEAT_OUT` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消出账',
  `REPEAT_BALANCE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消余额',
  `FREE_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '还未够750PV，即够750PV后可分红的部分',
  `ALREADY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '积分消费后的分红PV（可领货不可重分红）',
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '当天领货后的PV',
  PRIMARY KEY (`ACCOUNT_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户总账表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_account_201404`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_account_201404` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_account_201404` (
  `ACCOUNT_ID` INT(11) NOT NULL COMMENT '主键ID',
  `USER_ID` INT(11) NOT NULL COMMENT '用户主键ID',
  `ACCOUNT_DATE` DATE NULL DEFAULT NULL COMMENT '日期',
  `STAT` INT(11) NULL DEFAULT NULL COMMENT '总账状态',
  `BASE_IN` DOUBLE NULL DEFAULT NULL COMMENT '基本入账',
  `BASE_OUT` DOUBLE NULL DEFAULT NULL COMMENT '基本出账',
  `BASE_BALANCE` DOUBLE NULL DEFAULT NULL COMMENT '基本余额',
  `REPEAT_IN` DOUBLE NULL DEFAULT NULL COMMENT '重消入账',
  `REPEAT_OUT` DOUBLE NULL DEFAULT NULL COMMENT '重消出账',
  `REPEAT_BALANCE` DOUBLE NULL DEFAULT NULL COMMENT '重消余额',
  `FREE_PV` INT(11) NULL DEFAULT NULL COMMENT '未分红重消PV',
  `ALREADY_PV` INT(11) NULL DEFAULT NULL COMMENT '已分红未领货重消PV',
  `BUY_PV` INT(11) NULL DEFAULT NULL COMMENT '已领货重消PV',
  PRIMARY KEY (`ACCOUNT_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `slsaledb`.`user_account_log_201404`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_account_log_201404` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_account_log_201404` (
  `accountLogId` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NULL DEFAULT NULL,
  `actionTime` DATE NULL DEFAULT NULL,
  `actionDesc` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '动作摘要',
  `actionType` DECIMAL(6,0) NULL DEFAULT NULL COMMENT '0辅消,1重消',
  `baseIn` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '基本入账',
  `baseOut` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '基本出账',
  `baseBalance` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '基本余额',
  `repeatIn` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消入账',
  `repeatOut` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消出账',
  `repeatBalance` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '重消余额',
  PRIMARY KEY (`accountLogId`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户总账明细表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_buy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_buy` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_buy` (
  `BUY_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'BUY_ID',
  `BUY_TIME` DATE NULL DEFAULT NULL COMMENT '消费时间',
  `BONUS_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '拿奖金用户ID',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '消费PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '奖励PV',
  PRIMARY KEY (`BUY_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户重复消费记录表(个人拿钱再买)';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_buy_bonus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_buy_bonus` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_buy_bonus` (
  `BUY_BONUS_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'BUY_BONUS_ID',
  `BONUS_MONTH` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '月份',
  `CAL_TIME` DATE NULL DEFAULT NULL COMMENT '计算时间',
  `BONUS_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '下属总消费PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '总奖励PV',
  PRIMARY KEY (`BUY_BONUS_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户重复消费月奖励记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_cash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_cash` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_cash` (
  `CASH_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'CASH_ID',
  `CASH_TIME` DATE NULL DEFAULT NULL COMMENT '申请提现时间',
  `CASH_NUM` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '提现单号',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `CASH_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '提现PV',
  `CURRENCY` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '提现货币',
  `PV_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT 'PV转换率',
  `CASH_MONEY` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '提现金额',
  `NOTE` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '提现备注',
  `FEE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '手续费',
  `TAX` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '税费',
  `OTHER_FEE` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '其他费用',
  `BANK_NAME` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '提现银行名',
  `BANK_BRANCE` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '银行开户行名',
  `BANK_ACCOUNT` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '银行账号',
  `ACCOUNT_NAME` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '账号姓名',
  `STAT` DECIMAL(6,0) NULL DEFAULT NULL COMMENT '0申请提现,1审核通过,2转账完毕',
  `CREDITED_MONEY` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '到账金额',
  `CREDITED_TIME` DATE NULL DEFAULT NULL COMMENT '到账时间',
  `OPERATOR` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (`CASH_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户PV提现记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_pair_201312`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_pair_201312` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_pair_201312` (
  `PAIR_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'PAIR_ID',
  `DATE` DATE NULL DEFAULT NULL COMMENT '前一天的日期',
  `BONUS_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `LEFT_USER` DECIMAL(9,0) NULL DEFAULT NULL COMMENT '左用户总数',
  `RIGHT_USER` DECIMAL(9,0) NULL DEFAULT NULL COMMENT '右用户总数',
  `LEFT_KEEP` DECIMAL(9,0) NULL DEFAULT NULL COMMENT '左保留总数',
  `RIGHT_KEEP` DECIMAL(9,0) NULL DEFAULT NULL COMMENT '右保留总数',
  `EACH_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '从数据字典表取，目前是1000',
  `SUM_PAIR_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '总碰PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '对碰奖励PV',
  PRIMARY KEY (`PAIR_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户对碰记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_place` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_place` (
  `PLACE_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'PLACE_ID',
  `PLACE_TIME` DATE NULL DEFAULT NULL COMMENT '安置时间',
  `BONUS_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '拿奖金用户ID',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '消费PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '安置奖励PV',
  PRIMARY KEY (`PLACE_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户安置记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_point` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_point` (
  `POINT_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'POINT_ID',
  `BUY_TIME` DATE NULL DEFAULT NULL COMMENT '消费时间',
  `BONUS_USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '拿奖金用户ID',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '消费PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '奖励PV',
  PRIMARY KEY (`POINT_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户积分消费奖励记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_point_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_point_goods` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_point_goods` (
  `POINT_GOODS_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'POINT_GOODS_ID',
  `PICK_TIME` DATE NULL DEFAULT NULL COMMENT '领货时间',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '消费PV',
  `ORDER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '订单ID',
  PRIMARY KEY (`POINT_GOODS_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户积分领货记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_recharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_recharge` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_recharge` (
  `RECHARGE_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'RECHARGE_ID',
  `RECHARGE_TIME` DATE NULL DEFAULT NULL COMMENT '充值时间',
  `RECHARGE_NUM` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值单号',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `CURRENCY` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值货币',
  `RECHARGE_MONEY` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '充值金额',
  `NOTE` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '摘要备注',
  `CREDITED_MONEY` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '到账金额',
  `CREDITED_TIME` DATE NULL DEFAULT NULL COMMENT '到账时间',
  `AUDIT_USER` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '审核人',
  `PV_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT 'PV比率',
  `PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '兑换后PV值',
  `BANK_NAME` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值银行名',
  `BANK_ACCOUNT` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值账号名',
  `PLATFORM` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值平台',
  `PARAM` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '充值接口参数',
  PRIMARY KEY (`RECHARGE_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户汇款充值记录表';


-- -----------------------------------------------------
-- Table `slsaledb`.`user_refer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slsaledb`.`user_refer` ;

CREATE TABLE IF NOT EXISTS `slsaledb`.`user_refer` (
  `REFER_LOG_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'REFER_LOG_ID',
  `REFER_TIME` DATE NULL DEFAULT NULL COMMENT '推荐时间',
  `USER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `REFER_ID` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `BUY_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '消费PV',
  `BONUS_RATE` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '奖金比率',
  `BONUS_PV` DECIMAL(12,2) NULL DEFAULT NULL COMMENT '推荐奖励PV',
  PRIMARY KEY (`REFER_LOG_ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '用户推荐记录表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
